package com.latenighthack.basekit.demo

/**
 * Launches the generated terminal UI. `TuiApp` and `root` are generated by the TUI slice: `TuiApp`
 * builds the kotlin-inject component and runs the resolved root screen; `root<HomeViewModel>()` opens
 * the home feed, from which Enter on a row navigates to that item's detail and `[p]` opens the picker.
 */
fun main() {
    TuiApp {
        root<HomeViewModel>()
    }
}
