package com.latenighthack.basekit.demo

/**
 * Launches the generated terminal UI. `TuiApp` and `root` are generated by the TUI slice: `TuiApp`
 * builds the kotlin-inject component and runs the resolved root screen; `root<FeedViewModel>()` opens
 * the Feed (Home) screen, from which Enter on a row navigates to the Counter (Detail) screen.
 */
fun main() {
    TuiApp {
        root<FeedViewModel>()
    }
}
